server:
  port: 8081
spring:
  application:
  name: movieflixneo

  datasource:
    url: jdbc:postgresql://localhost:5432/movieflixneo
    username: postgres
    password: yacs1997
    driver-class-name: org.postgresql.Driver

  jpa:
    database-plataform: org.hibernate.dialect.PostgresSQLDialect
    show-sql: true


  flyway:
    enabled: true
